[package]
name = "ir_core"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
dyn_type = {path = "../dyn_type"}
ir_common = {path = "../common", features = ["proto_inplace"]}
pegasus_client = {path = "../../pegasus/clients/rust/client"}
prost = "0.8"
runtime = {path = "../runtime"}
vec_map = "0.8.2"

[profile.release]
lto = true
panic = "abort"



