[package]
name = "ir_core"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
dyn_type = {path = "../dyn_type"}
prost = "0.7"
pegasus_common = { path = "../../pegasus/common" }
tonic = "0.4"
vec_map = "0.8.2"

[build-dependencies]
tonic-build = "0.4"

[profile.release]
lto = true
panic = "abort"

[features]
proto_inplace = []
