[package]
name = "ir_common"
version = "0.1.0"
edition = "2018"

[dependencies]
dyn_type = {path = "../../../dyn_type"}
pegasus_common = { path = "../../../engine/pegasus/common" }
prost = "0.9"
prost-types = "0.9"
prost-wkt = "0.3"
prost-wkt-types = "0.3"
serde = { version = "1.0", features = ["derive"] }
tonic = "0.4"

[build-dependencies]
prost-build = "0.9"
prost-wkt-build = "0.3"

[features]
default = []
proto_inplace = []
