[package]
name = "ir_common"
version = "0.1.0"
edition = "2018"

[dependencies]
dyn_type = {path = "../../../dyn_type"}
prost = "0.8"
pegasus_common = { path = "../../../engine/pegasus/common" }
tonic = "0.4"

[build-dependencies]
tonic-build = "0.4"

[features]
default = []
proto_inplace = []
