[package]
name = "runtime"
version = "0.1.0"
edition = "2018"

[dependencies]
dyn_type = {path = "../dyn_type"}
ir_common = {path = "../common", features = ["proto_inplace"]}
pegasus_common = { path = "../../pegasus/common" }

[profile.release]
lto = true
panic = "abort"