[package]
name = "runtime"
version = "0.1.0"
edition = "2018"

[dependencies]
dyn_type = {path = "../dyn_type"}
ir_common = {path = "../common", features = ["proto_inplace"]}
pegasus_common = { path = "../../pegasus/common" }
pegasus = { path = "../../pegasus/pegasus" }
pegasus_server = { path = "../../pegasus/server" }
pegasus_client = {path = "../../pegasus/clients/rust/client"}
graph_store = {path = "../../../graph_store"}
lazy_static = "1.3.0"
prost = "0.8"
log = "0.4"

[profile.release]
lto = true
panic = "abort"