[package]
name = "grel_core"
version = "0.1.0"
edition = "2018"

[dependencies]
dyn_type = {path = "../dyn_type"}
prost = "0.7"
tonic = "0.4"

[build-dependencies]
tonic-build = "0.4"

[profile.release]
lto = true
panic = "abort"

[features]
proto_inplace = []
