name: GraphScope GAIA CI

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'research/**'
      - '.github/workflows/gaia.yml'
      - '!research/**.md'
  pull_request:
    branches:
      - main
    paths:
      - 'research/**'
      - '.github/workflows/gaia.yml'
      - '!research/**.md'

jobs:
  gaia-test:
    runs-on: ubuntu-20.04
    if: true
    defaults:
      run:
        shell: bash --noprofile --norc -eo pipefail {0}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies
      run: |
        # Due to an observation of changing hostname in github runners,
        # append 127.0.0.1 to etc/hosts to avoid DNS lookup.
        r=`cat /etc/hosts | grep $(hostname) || true`
        if [ -z "${r}" ];then export hn=$(hostname); sudo -E bash -c 'echo "127.0.0.1 ${hn}" >> /etc/hosts'; fi
        cat /etc/hosts

        # install dependencies
        ${GITHUB_WORKSPACE}/scripts/install_deps.sh --dev --verbose

    - name: Build GraphScope
      run: |
        source ${HOME}/.graphscope_env
        make BUILD_TYPE=debug

    - name: Build Ir on Experimental Store
      run: |
        source ${HOME}/.graphscope_env
        cd ${GITHUB_WORKSPACE}/research/query_service/ir/compiler
        make build

    - name: Build Ir on Groot Store
      run: |
        source ${HOME}/.graphscope_env
        cd ${GITHUB_WORKSPACE}/interactive_engine
        mvn clean install -DskipTests -Pv2

    - name: Ir Unit Test
      run: |
        source ${HOME}/.graphscope_env
        cd ${GITHUB_WORKSPACE}/research/query_service/ir/compiler && make test

    - name: Ir Integration Test on Experimental Store
      run: |
        source ${HOME}/.graphscope_env
        cd ${GITHUB_WORKSPACE}/research/query_service/ir/compiler && ./ir_exprimental_ci.sh

    - name: Ir Integration Test on Groot Store
      run: |
        source ${HOME}/.graphscope_env
        cd ${GITHUB_WORKSPACE}/interactive_engine/ir-adaptor && ./ir_groot_ci.sh

